all:
	@echo "与命令相关的变量"
	@echo $(AR)
	@echo $(AS)
	@echo $(CC)
	@echo $(CXX)
	@echo $(CPP)
	@echo $(LEX)
	@echo $(YACC)
	@echo $(RM)
	@echo "与参数相关的变量"
	@echo $(ARFLAGS)
	@echo $(ASFLAGS)
	@echo $(CFLAGS)
	@echo $(CXXFLAGS)
	@echo $(LDFLAGS)
	@echo $(LFLAGS)
	@echo $(YFLAGS)
